### ISSUE TITLE
imu::getOrientation()

### ISSUE THREAD

**Issue by aafeliz** [r3n33/EddieBalance#6]
on line 104 you have an if statement and left the else blank.
I found outside sources where the else was defined as the following 
i2cPitch = (float) atan2(-ax,(ay_sin(i2cRoll) + az_cos(i2cRoll)));

**Comment by r3n33** [comment]
Thank you! I'll check it out when possible. It's been a little while since Eddie has been powered up o_O

**Comment by r3n33** [comment]
The else was not blank, only tabbed over excessively. I'll apply formatting to the files with tonight's update so the code is easier to read.
